### DISCUSSION TITLE
Unable to View ESPHome Logs

### DISCUSSION THREAD

**Discussion by Photo64** [tube0013/tube_gateways#112] [Q&A] [answered]
I added the WT32-ETH01 ethernet BTProxy however when I try to view the logs in I get an error. Shouldn't I be able to view the logs? 
This is the error I see:
**INFO Reading configuration /config/esphome/wt32-eth01-bt-proxy.yaml...
Failed config

ethernet: [source /config/esphome/.esphome/packages/f8744889/wt32-eth01.yaml:17]
  
  This feature is only available with frameworks ['arduino'].
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16**

Also, This is all I have in the yaml file, is this correct?
```
substitutions:
  name: wt32-eth01-bt-proxy
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/wt32-eth01.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
```
