### ISSUE TITLE
Unable to update or connect to zigbee2mqtt with cc2652p2_poe.

### ISSUE THREAD

**Issue by Eagleman7** [tube0013/tube_gateways#40]
Trying to get the cc2652p2_poe working, however I keep getting this error in zigbee2mqtt:
```
Zigbee2MQTT:error 2021-11-01 17:39:16: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:63:27)
    at Controller.start (/app/lib/controller.js:116:27)
    at start (/app/index.js:95:5)
```

So I decided to install firmware to see if this resolves the issue. However when I click `Prep the cc2652p2 for firmware update` nothing happens in the debug log. This is after waiting 2 minutes:
![image](https://user-images.githubusercontent.com/4787591/139708092-c96013ac-ef9c-4226-8d7e-6e9a6368517a.png)
Switching browsers or incognito also doesnt work. The only button that seems to do something is restart, which it then does.

Anything I can do to resolve this?

**Comment by tube0013** [comment]
Hi Sorry for the trouble. If nothing is showing in the Debug log after using any of the buttons above it likely means the connection between the browser and the device has dropped. 

You can you try and re-flash the ESP32/ESPHome binary - .bin available here:  https://github.com/tube0013/tube_gateways/tree/main/tube_poe_coordinator

this is done on the Devices web page via the OTA option.

 you can also do it over usb (I like the esphome flasher app) - this method clears out the memory first. the USB port is accessible if you open the case. DO NOT keep powered ethernet plugged in if you use this - there is also a warning on the PCB about this.

**Comment by Eagleman7** [comment]
Thanks, the buttons are back!
![image](https://user-images.githubusercontent.com/4787591/139716421-98e5c6f2-f7a4-4b64-8c45-1afe4e7ef4ca.png)
Do I still need to do the update using these files? https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.x.0/bin

**Comment by tube0013** [comment]
the zigbee module comes pre-flashed with the latest fw from there, so there should be no need to update it.

when you try to connect z2m to the device, do you see anything in the debug log now?

**Comment by Eagleman7** [comment]
Maybe I don't understand the toggle, I need to wait for something to show in the debug log before I can update, right?

**Comment by tube0013** [comment]
There is most likely no need to update the fw on the zigbee module. it comes preflashed. the issues you are describing are with the ESP32 device. - getting connected and staying connected. 

Are you seeing any logs in the Debug Log in the browser? even when you reboot the device with the button it should show something. It should also show when a serial device connects/disconnects. if nothing is showing we need to troubleshoot the esp32's ethernet connection. maybe try a fw bin with a static ip set.

**Comment by Eagleman7** [comment]
I never saw anything appearing in the debug log at all stages.

![image](https://user-images.githubusercontent.com/4787591/139717700-b470c628-7011-4971-b2ea-836ba457c3de.png)


```
[root@control cc2538-bsl]# python3 cc2538-bsl.py -p socket://zigbee-gateway.corp.pootenterprise.com:6638  -evw ../CC1352P2_CC2652P_launchpad_coordinator_20210708.hex
Opening port socket://zigbee-gateway.corp.example.com:6638, baud 500000
Reading data from ../CC1352P2_CC2652P_launchpad_coordinator_20210708.hex
Firmware file: Intel Hex
Connecting to target...
ERROR: Timeout waiting for ACK/NACK after 'Get Status (0x23)'
```

**Comment by tube0013** [comment]
the Firmware update toggle runs a script on the ESP32 that toggles on the BSL button, toggles the Reset of the zigbee module, then waits about 10 secs releases the BSL, and prints a message to use the command line update tool to flash the module. 

Again it shouldn't be necessary though, I flash all modules and test them, then add them to the boards, test again through the esp32 and then reset the NVRAM all over the ethernet connection before shipping the devices.

**Comment by Eagleman7** [comment]
Lets skip the firmware through cc2538-bsl.pu for now then :). zigbee2mqtt is still having issues connecting: 
![image](https://user-images.githubusercontent.com/4787591/139718235-2123e726-cf14-40d6-8cda-c7bb73592650.png)

**Comment by tube0013** [comment]
is Z2M pointing to an IP or a hostname? if hostname try the ip

**Comment by Eagleman7** [comment]
Tried using IP, same problem :(

```
advanced:
  homeassistant_discovery_topic: homeassistant    
  homeassistant_status_topic: homeassistant/status
  last_seen: ISO_8601
  log_level: info
  log_output:
  - console
  network_key: GENERATE
  pan_id: GENERATE
device_options:
  retain: true
experimental:
  new_api: true
frontend:
  port: 8080
homeassistant: true
mqtt:
  base_topic: zigbee2mqtt
  include_device_information: true
  password: admin
  server: mqtt://mosquitto.home.svc.cluster.local
  user: admin
permit_join: true
serial:
  port: tcp://192.168.3.10:6638
```

Can I test that port from my computer instead, to see if something is running on that port?
