### ISSUE TITLE
Q: what do I need to fill in for Devices: on zigbee2mqtt docker-compose.yml

### ISSUE THREAD

**Issue by ranrinc** [tube0013/tube_gateways#52]
What should I input as devices on this scenario?

`tcp://IPADDRESS:6638:tcp://IPADDRESS:6638`

```
version: '3.8'
services:
  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "./mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    container_name: zigbee2mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
```
